### ISSUE TITLE
Make Order number unique in db

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-order#113] opened 2019-09-12 12:00 UTC
While we require and generate unique order numbers, there are no restrictions in db for it

**Comment by 5309** [comment] 2019-09-13 11:15
We generate unique Order numbers by default, but we should not restrict Order number to be unique. For example, the same Virto Commerce installation might be used by a few legal entities with the same kind of Order number sequences. In this case, there might be few orders with the same Order number. 

The problem is that API method /api/order/customerOrders/number/{number} is designed to return only one Order by number. 

@tatarincev how it can be resolved?

**Comment by asvishnyakov** [comment] 2019-09-13 13:26
Not only this one, but in storefront too

**Comment by tatarincev** [comment] 2019-09-18 09:13
I think what this method `/api/order/customerOrders/number/{number}` should be marked as `Obsoleted` with future remove

**Comment by OlegoO** [comment] 2024-12-20 13:58
Resolved

**Closed by OlegoO** 2024-12-20 13:58 UTC
Labels: bug, client request
